"""fixing members ID1

Revision ID: 1d0bf291f48a
Revises: ce7e399d0506
Create Date: 2026-06-25 17:59:39.476814

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d0bf291f48a"
down_revision: str | Sequence[str] | None = "ce7e399d0506"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("members", "id", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
