"""allow head_id to be null

Revision ID: 828d7e30f902
Revises: d564f9b3d132
Create Date: 2026-07-01 13:18:19.511110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828d7e30f902'
down_revision: Union[str, Sequence[str], None] = 'd564f9b3d132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('families_original_governor_id_fkey'), 'families', type_='foreignkey')
    op.drop_constraint(op.f('families_current_governor_id_fkey'), 'families', type_='foreignkey')
    op.drop_column('families', 'current_governor_id')
    op.drop_column('families', 'original_governor_id')
    op.drop_index(op.f('ix_members_full_name_trgm'), table_name='members', postgresql_ops={'full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_members_full_name_trgm'), 'members', ['full_name'], unique=False, postgresql_ops={'full_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('families', sa.Column('original_governor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('families', sa.Column('current_governor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('families_current_governor_id_fkey'), 'families', 'governors', ['current_governor_id'], ['id'])
    op.create_foreign_key(op.f('families_original_governor_id_fkey'), 'families', 'governors', ['original_governor_id'], ['id'])
    # ### end Alembic commands ###
