"""add pg_trgm extension and index

Revision ID: d564f9b3d132
Revises: 1d0bf291f48a
Create Date: 2026-06-27 13:59:30.776352

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d564f9b3d132"
down_revision: str | Sequence[str] | None = "1d0bf291f48a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Enable the extension
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # 2. Create a GIN index on the full_name column.
    # This makes ILIKE searches lightning-fast instead of scanning the whole table.
    op.create_index(
        "ix_members_full_name_trgm",
        "members",
        ["full_name"],
        postgresql_using="gin",
        postgresql_ops={"full_name": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_members_full_name_trgm", table_name="members")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm;")
    # ### end Alembic commands ###
